#!/usr/bin/env bash
# setup_vps.sh — Deploy RetailIQ backend on a fresh Ubuntu/Debian VPS.
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/hugoseligman-lang/retailiq/master/setup_vps.sh | bash
# Or after cloning:
#   bash setup_vps.sh
#
# Required env vars (set before running, or edit the .env section below):
#   GOOGLE_VISION_API_KEY
#   ANTHROPIC_API_KEY
#   BRIDGE_SECRET          (any random string — copy to camera_bridge.py on the store side)
#
# Optional:
#   STORE_NAME  STORE_LAT  STORE_LON  STORE_STATE  FLASK_PORT

set -e

PORT="${FLASK_PORT:-5050}"
REPO="https://github.com/hugoseligman-lang/retailiq.git"
INSTALL_DIR="/opt/retailiq"
SERVICE="retailiq"

echo "============================================"
echo "  RetailIQ VPS Setup"
echo "  Install dir : $INSTALL_DIR"
echo "  Port        : $PORT"
echo "============================================"

# ── System packages ──────────────────────────────────────────────────────────

echo "[1/7] Updating packages..."
apt-get update -qq
apt-get install -y -qq python3 python3-pip python3-venv git \
    libgl1 libglib2.0-0 libsm6 libxext6 libxrender-dev

# ── Clone / update repo ───────────────────────────────────────────────────────

echo "[2/7] Cloning repo..."
if [ -d "$INSTALL_DIR/.git" ]; then
    git -C "$INSTALL_DIR" pull --ff-only
else
    git clone "$REPO" "$INSTALL_DIR"
fi

cd "$INSTALL_DIR"

# ── Python venv + deps ────────────────────────────────────────────────────────

echo "[3/7] Installing Python dependencies..."
python3 -m venv .venv
.venv/bin/pip install --quiet --upgrade pip
# Use headless OpenCV on servers (no display needed)
.venv/bin/pip install --quiet \
    flask flask-cors python-dotenv requests anthropic \
    google-cloud-vision opencv-python-headless numpy \
    open-meteo holidays

# ── .env ─────────────────────────────────────────────────────────────────────

echo "[4/7] Writing backend/.env..."
BRIDGE_SECRET="${BRIDGE_SECRET:-$(openssl rand -hex 16)}"

cat > backend/.env <<EOF
# RetailIQ VPS configuration — generated by setup_vps.sh
CAMERA_MODE=vps
STORE_NAME=${STORE_NAME:-My Store}
STORE_LAT=${STORE_LAT:--33.8688}
STORE_LON=${STORE_LON:-151.2093}
STORE_STATE=${STORE_STATE:-NSW}
FLASK_HOST=0.0.0.0
FLASK_PORT=${PORT}
GOOGLE_VISION_API_KEY=${GOOGLE_VISION_API_KEY:-REPLACE_ME}
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-REPLACE_ME}
BRIDGE_SECRET=${BRIDGE_SECRET}
EOF

echo ""
echo "  *** Copy this BRIDGE_SECRET to your camera_bridge .env ***"
echo "  BRIDGE_SECRET=${BRIDGE_SECRET}"
echo ""

# ── systemd service ───────────────────────────────────────────────────────────

echo "[5/7] Installing systemd service..."
cat > /etc/systemd/system/${SERVICE}.service <<EOF
[Unit]
Description=RetailIQ Backend
After=network.target

[Service]
Type=simple
WorkingDirectory=${INSTALL_DIR}/backend
ExecStart=${INSTALL_DIR}/.venv/bin/python main.py
Restart=always
RestartSec=5
StandardOutput=journal
StandardError=journal
Environment=PYTHONUNBUFFERED=1

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable "$SERVICE"
systemctl restart "$SERVICE"

# ── Firewall ──────────────────────────────────────────────────────────────────

echo "[6/7] Configuring firewall..."
if command -v ufw &>/dev/null; then
    ufw allow "$PORT"/tcp
    echo "  ufw: port $PORT allowed"
fi

# ── Done ──────────────────────────────────────────────────────────────────────

echo "[7/7] Done."
echo ""
PUBLIC_IP=$(curl -sf https://api.ipify.org || echo "<your-vps-ip>")
echo "============================================"
echo "  RetailIQ is running!"
echo ""
echo "  Backend URL : http://${PUBLIC_IP}:${PORT}"
echo "  Health check: http://${PUBLIC_IP}:${PORT}/api/health"
echo ""
echo "  Dashboard (Vercel) — paste this URL into Settings:"
echo "    http://${PUBLIC_IP}:${PORT}"
echo ""
echo "  Store camera bridge .env:"
echo "    VPS_URL=http://${PUBLIC_IP}:${PORT}"
echo "    BRIDGE_SECRET=${BRIDGE_SECRET}"
echo "============================================"
echo ""
echo "  To view logs : journalctl -fu $SERVICE"
echo "  To stop      : systemctl stop $SERVICE"
